# -*- Makefile -*-
#
# Makefile.PSP - Makefile rules for Sony Play Station Portable Firmware version 1.0
#   Thanks Shiikuru-san
#

PSPPRE = $(shell psp-config --psp-prefix)
PSPDEV = $(shell psp-config --pspdev-path)
PSPSDK = $(shell psp-config --pspsdk-path)

INCS  = $(shell $(PSPPRE)/bin/sdl-config --cflags) -I$(PSPPRE)/include/freetype2 -Ithird_party/libpspav/include -Ithird_party
LIBS  = -L$(PSPPRE)/lib -L$(PSPSDK)/lib -L$(PSPDEV)/lib
LIBS += $(SDL_VIDEO_OBJ) $(SDL_AUDIO_OBJ)
LIBS += third_party/libpspav/libpspav.a -lpspvram -lpspmpeg -lpspatrac3
LIBS += third_party/sdl-ttf/SDL_ttf.o -lSDL_image -lSDL_mixer -lSDLmain -lSDL -lfreetype -lbz2 -ljpeg -lpng -lz -lmad $(TREMOR_LIB) -logg -lstdc++ -lsupc++ -lm

# Include PSPSDK and Libc Headers
INCS += -I$(PSPSDK)/include -I$(PSPDEV)/include -I$(PSPPRE)/include

# Link PSP platform libraries last; libc and user stubs come from psp-gcc.
# Let psp-gcc append utility/RTC/net-inet after libc. Listing those
# archives here splits their imports when libc pulls in more stubs later.
LIBS +=  -lpspirkeyb -lpsppower -lpspdebug -lpspgu -lpspdisplay -lpsphprm -lpspaudio -lpspge -lpspctrl


# with OggVorbis (Tremor) in PDA size (QVGA)
#DEFS = -DPSP -DPDA -DBPP16 -DMP3_MAD -DUSE_OGG_VORBIS -DINTEGER_OGG_VORBIS
# with OggVorbis (Tremor) in PSP size (360x270)
GAME_ID ?= ONSP00001
DEFS = -DONS_PSP_GAME_ID=\"$(GAME_ID)\" -DPSP -DPDA -DPDA_PSP -DBPP16 -DMP3_MAD -DUSE_OGG_VORBIS -DINTEGER_OGG_VORBIS -DONS_CN_CP936
# with OggVorbis (Tremor) in PSP size (384x288)
#DEFS = -DPSP -DPDA -DPDA_PSP2 -DBPP16 -DMP3_MAD -DUSE_OGG_VORBIS -DINTEGER_OGG_VORBIS

EXESUFFIX = .elf
OBJSUFFIX = .o

.SUFFIXES:
.SUFFIXES: $(OBJSUFFIX) .cpp .h

CC = psp-g++ 
LD = psp-gcc -o

CFLAGS = -g -G0 -O2 -Wall -Wpointer-arith -fno-exceptions -fno-rtti -fno-check-new -pipe -c $(INCS) $(DEFS)
RM = rm -f

TARGET = EBOOT.PBP
EXT_OBJS = MadWrapper$(OBJSUFFIX) PSPPmfPlayer$(OBJSUFFIX) PSPDiagnostic$(OBJSUFFIX)
PMF_LIB = third_party/libpspav/libpspav.a
TREMOR_LIB = third_party/tremor/libvorbisidec.a
SDL_VIDEO_OBJ = third_party/sdl-psp/SDL_pspvideo.o
SDL_AUDIO_OBJ = third_party/sdl-psp/SDL_pspaudio.o


# onscripter.elf -> EBOOT.PBP for PSP Firmware version 1.0

STRIP    = psp-strip
# Request extended user RAM on supported PSP models.
MKSFO    = mksfoex -d MEMSIZE=1
PACK_PBP = pack-pbp

PSP_TARGET       = onscripter$(EXESUFFIX)
PSP_TARGET_STRIP = onscripter_strip$(EXESUFFIX)
PSP_EBOOT_TITLE ?= ONScripter PSP
PSP_EBOOT_SFO    = PARAM.SFO
PSP_EBOOT_ICON   = NULL
PSP_EBOOT_ICON1  = NULL
PSP_EBOOT_UNKPNG = NULL
PSP_EBOOT_PIC1   = NULL
PSP_EBOOT_SND0   = NULL
PSP_EBOOT_PSAR   = NULL

EBOOT.PBP : $(PSP_TARGET_STRIP) $(PSP_EBOOT_SFO)
	$(PACK_PBP) EBOOT.PBP $(PSP_EBOOT_SFO) $(PSP_EBOOT_ICON)  \
		$(PSP_EBOOT_ICON1) $(PSP_EBOOT_UNKPNG) $(PSP_EBOOT_PIC1)  \
		$(PSP_EBOOT_SND0)  $(PSP_TARGET_STRIP) $(PSP_EBOOT_PSAR)

$(PSP_EBOOT_SFO) : Makefile.PSP
	$(MKSFO) '$(PSP_EBOOT_TITLE)' $(PSP_EBOOT_SFO)

$(PSP_TARGET_STRIP) : $(PSP_TARGET)
	$(STRIP) $(PSP_TARGET) -o $(PSP_TARGET_STRIP)

include Makefile.onscripter

.PHONY: pmf-lib
pmf-lib:
	$(MAKE) -C third_party/libpspav

$(PSP_TARGET): pmf-lib $(SDL_VIDEO_OBJ) tremor-lib $(SDL_AUDIO_OBJ) third_party/sdl-ttf/SDL_ttf.o

third_party/sdl-ttf/SDL_ttf.o: third_party/sdl-ttf/SDL_ttf.c
	psp-gcc -O2 -G0 -DHAVE_ALLOCA_H -DHAVE_ALLOCA $(INCS) -c $< -o $@

.PHONY: tremor-lib
tremor-lib:
	$(MAKE) -C third_party/tremor

$(SDL_VIDEO_OBJ): third_party/sdl-psp/src/video/psp/SDL_pspvideo.c third_party/sdl-psp/PSP_movie_gpu.inc PSPGpuGeometry.h
	psp-gcc -O2 -G0 -Wall -MMD -MP -I. -I$(PSPPRE)/include/SDL -I$(PSPSDK)/include -c $< -o $@

$(SDL_AUDIO_OBJ): third_party/sdl-psp/src/audio/psp/SDL_pspaudio.c PSPDiagnostic.h
	psp-gcc -O2 -G0 -Wall -MMD -MP -I. -I$(PSPPRE)/include/SDL -I$(PSPSDK)/include -c $< -o $@

-include $(SDL_VIDEO_OBJ:.o=.d) $(SDL_AUDIO_OBJ:.o=.d)

PSPPmfPlayer$(OBJSUFFIX): PSPPmfPlayer.h PSPPmfPath.h PSPFastPixels.h PSPPmfTiming.h third_party/libpspav/include/pspav.h
ONScripterLabel$(OBJSUFFIX) AnimationInfo$(OBJSUFFIX): PSPFastPixels.h
$(filter ONScripterLabel%,$(OBJS)): PSPBackgroundCache.h
PSPPmfPlayer$(OBJSUFFIX): PSPPmfGpu.inc PSPGpuGeometry.h PSPBackgroundCache.h PSPExactMovie.h
ONScripterLabel_animation$(OBJSUFFIX): ONSPmfGpu.inc PSPPmfPlayer.h
ONScripterLabel_sound$(OBJSUFFIX): ONSPcmChunk.inc
ONScripterLabel_event$(OBJSUFFIX): ONSAudioEvents.inc ONSAudioGeneration.h
$(filter ONScripterLabel%,$(OBJS)): ONSAudioGeneration.h

ScriptParser.o ScriptHandler.o DirectReader.o ONScripterLabel_file.o ONScripterLabel_command.o: PSPSavedata.h

ONScripterLabel_command.o: PSPSavedataDescription.h ONSSaveText.h PSPSavedataMac.h vendor/tiny-aes/aes.c vendor/tiny-aes/aes.h

$(OBJS): ONScripterLabel.h ScriptParser.h PSPGameConfig.h
ONScripterLabel_image.o: ONSMaskGain.h

# overriding
clean :
	$(MAKE) -C third_party/tremor clean
	$(MAKE) -C third_party/libpspav clean
	$(RM) $(TARGET)
	$(RM) $(PSP_TARGET) $(PSP_TARGET_STRIP) $(PSP_EBOOT_SFO)
	$(RM) *.o
	$(RM) $(SDL_VIDEO_OBJ) $(SDL_VIDEO_OBJ:.o=.d) $(SDL_AUDIO_OBJ) $(SDL_AUDIO_OBJ:.o=.d)
